{"name": " -- @1.4 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given user able to launch browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667381369375, "stop": 1667381372246}, {"name": "When user able to click on signin button", "status": "skipped", "start": 1667381372253, "stop": 1667381372253}, {"name": "Then user able to click on the continue with apple", "status": "skipped", "start": 1667381372253, "stop": 1667381372253}, {"name": "When user enter the  apple id \"pavan@email.com\"", "status": "skipped", "start": 1667381372253, "stop": 1667381372253}, {"name": "And user click on the next icon", "status": "skipped", "start": 1667381372253, "stop": 1667381372253}, {"name": "Then user enter the apple id password \"12busu\"", "status": "skipped", "start": 1667381372253, "stop": 1667381372253}, {"name": "And user click on the next button", "status": "skipped", "start": 1667381372253, "stop": 1667381372253}], "parameters": [{"name": "apple_id", "value": "pavan@email.com"}, {}, {"name": "password", "value": "12busu"}], "start": 1667381369369, "stop": 1667381372253, "uuid": "d35d09b4-12bf-4925-bcb2-16c022e805f5", "historyId": "d7ae6c78ea0901242c643626276aa69e", "fullName": "signin by apple id: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "signin by apple id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}