{"name": " -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given user able to launch browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667381307608, "stop": 1667381343089}, {"name": "When user able to click on signin button", "status": "skipped", "start": 1667381343097, "stop": 1667381343097}, {"name": "Then user able to click on the continue with apple", "status": "skipped", "start": 1667381343097, "stop": 1667381343097}, {"name": "When user enter the  apple id \"khadar123@icloud.com\"", "status": "skipped", "start": 1667381343097, "stop": 1667381343097}, {"name": "And user click on the next icon", "status": "skipped", "start": 1667381343097, "stop": 1667381343097}, {"name": "Then user enter the apple id password \"122455\"", "status": "skipped", "start": 1667381343097, "stop": 1667381343097}, {"name": "And user click on the next button", "status": "skipped", "start": 1667381343097, "stop": 1667381343097}], "parameters": [{"name": "apple_id", "value": "khadar123@icloud.com"}, {}, {"name": "password", "value": "122455"}], "start": 1667381307608, "stop": 1667381343097, "uuid": "a7fdc017-f58b-4d81-8831-335574f4cf94", "historyId": "e353e5e4db562856419e421c5c7b2cf0", "fullName": "signin by apple id: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "signin by apple id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}