{"name": " -- @1.5 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given user able to launch browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667381372263, "stop": 1667381374982}, {"name": "When user able to click on signin button", "status": "skipped", "start": 1667381374985, "stop": 1667381374985}, {"name": "Then user able to click on the continue with apple", "status": "skipped", "start": 1667381374985, "stop": 1667381374985}, {"name": "When user enter the  apple id \"hussain1@icloud.com\"", "status": "skipped", "start": 1667381374985, "stop": 1667381374986}, {"name": "And user click on the next icon", "status": "skipped", "start": 1667381374986, "stop": 1667381374986}, {"name": "Then user enter the apple id password \"khadar\"", "status": "skipped", "start": 1667381374986, "stop": 1667381374986}, {"name": "And user click on the next button", "status": "skipped", "start": 1667381374986, "stop": 1667381374986}], "parameters": [{"name": "apple_id", "value": "hussain1@icloud.com"}, {}, {"name": "password", "value": "khadar"}], "start": 1667381372257, "stop": 1667381374986, "uuid": "fca57665-5d3a-456e-bbc5-e220732a9a2c", "historyId": "f9d95dfcc2703297df180a53b1e3b0d7", "fullName": "signin by apple id: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "signin by apple id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}