{"name": " -- @1.3 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given user able to launch browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=107.0.5304.88)\n\n", "trace": "  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\continue_appleId.py\", line 13, in step_impl\n    context.driver.get(url)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\khada\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667381356863, "stop": 1667381369363}, {"name": "When user able to click on signin button", "status": "skipped", "start": 1667381369367, "stop": 1667381369367}, {"name": "Then user able to click on the continue with apple", "status": "skipped", "start": 1667381369367, "stop": 1667381369367}, {"name": "When user enter the  apple id \"raj987@icloud.com\"", "status": "skipped", "start": 1667381369367, "stop": 1667381369367}, {"name": "And user click on the next icon", "status": "skipped", "start": 1667381369367, "stop": 1667381369367}, {"name": "Then user enter the apple id password \"cloud12\"", "status": "skipped", "start": 1667381369367, "stop": 1667381369367}, {"name": "And user click on the next button", "status": "skipped", "start": 1667381369367, "stop": 1667381369367}], "parameters": [{"name": "apple_id", "value": "raj987@icloud.com"}, {}, {"name": "password", "value": "cloud12"}], "start": 1667381356859, "stop": 1667381369367, "uuid": "313c59e5-7a64-4a5d-940d-db590d048e5d", "historyId": "82a552c1e8baa94ebb50fb445bce315c", "fullName": "signin by apple id: ", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "signin by apple id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}